import { FeedCard, Match, Message, Like, Icebreaker, City, KundliTier } from '@/types';

const avatarUrl = (seed: string) =>
  `https://api.dicebear.com/7.x/avataaars/svg?seed=${seed}`;

function getCulturalBadge(score: number): 'Excellent' | 'Good' | 'Fair' {
  if (score >= 80) return 'Excellent';
  if (score >= 60) return 'Good';
  return 'Fair';
}

function getKundliTier(score: number): KundliTier {
  if (score >= 28) return 'Ideal';
  if (score >= 20) return 'Good';
  if (score >= 14) return 'Fair';
  return 'Low';
}

export const mockProfiles: FeedCard[] = [
  {
    user: {
      id: '1',
      phone: '+919876543210',
      first_name: 'Priya',
      date_of_birth: '1998-03-15',
      age: 27,
      gender: 'woman',
      city: 'Mumbai',
      country: 'India',
      intent: 'marriage',
      show_me: 'men',
      bio: 'Chai lover, book nerd, and proud Sindhi. Looking for someone who can match my energy at a Chaliha Sahib celebration and also enjoy a quiet Sunday morning.',
      verified: true,
      profile_completeness: 85,
      created_at: '2024-01-15',
      updated_at: '2024-03-10',
    },
    photos: [
      { id: 'p1', user_id: '1', url: avatarUrl('Priya'), is_primary: true, order: 0, verified: true, created_at: '2024-01-15' },
      { id: 'p1b', user_id: '1', url: avatarUrl('PriyaB'), is_primary: false, order: 1, verified: false, created_at: '2024-01-15' },
      { id: 'p1c', user_id: '1', url: avatarUrl('PriyaC'), is_primary: false, order: 2, verified: false, created_at: '2024-01-15' },
    ],
    basics: {
      user_id: '1',
      height_cm: 165,
      education: 'MBA, IIM Ahmedabad',
      work_title: 'Product Manager',
      company: 'Google',
      drinking: 'socially',
      smoking: 'never',
      wants_kids: 'want',
      settling_timeline: '1_2_years',
      exercise: 'often',
    },
    sindhi: {
      user_id: '1',
      sindhi_fluency: 'fluent',
      religion: 'hindu',
      gotra: 'Lohana',
      generation: 'sindhi_born',
      dietary: 'vegetarian',
      festivals: ['Chaliha Sahib', 'Diwali', 'Jhulelal Jayanti'],
      family_involvement: 'somewhat',
    },
    personality: {
      user_id: '1',
      prompts: [
        { prompt_id: '1', prompt_text: 'A life goal of mine', answer: 'Building a startup that connects Sindhi artisans with the world' },
        { prompt_id: '2', prompt_text: 'The way to my heart is', answer: 'Good dal pakwan and a genuine conversation' },
        { prompt_id: '3', prompt_text: 'My Sindhi superpower', answer: 'I can cook the best sai bhaji you have ever tasted' },
      ],
      interests: ['Reading', 'Travel', 'Cooking', 'Yoga', 'Photography'],
      bio: 'Chai lover, book nerd, and proud Sindhi.',
      languages: ['Sindhi', 'Hindi', 'English'],
    },
    cultural_score: 92,
    cultural_badge: 'Excellent',
    cultural_breakdown: { fluency: 18, religion: 16, dietary: 14, festivals: 16, family_values: 14, generation: 14 },
    kundli_score: 28,
    kundli_tier: 'Ideal',
    kundli_breakdown: { varna: 1, vashya: 2, tara: 3, yoni: 4, graha_maitri: 5, gana: 6, bhakut: 4, nadi: 3 },
    common_interests: ['Travel', 'Cooking', 'Reading'],
    distance_km: 5,
    daily_prompt_answer: 'Today I am grateful for family video calls that bridge continents',
  },
  {
    user: {
      id: '2',
      phone: '+919876543211',
      first_name: 'Rahul',
      date_of_birth: '1996-07-22',
      age: 29,
      gender: 'man',
      city: 'Pune',
      country: 'India',
      intent: 'marriage',
      show_me: 'women',
      bio: 'Software engineer by day, amateur musician by night. My nani says I need to find a good Sindhi girl, and honestly she is right.',
      verified: true,
      profile_completeness: 90,
      created_at: '2024-02-01',
      updated_at: '2024-03-08',
    },
    photos: [
      { id: 'p2', user_id: '2', url: avatarUrl('Rahul'), is_primary: true, order: 0, verified: true, created_at: '2024-02-01' },
      { id: 'p2b', user_id: '2', url: avatarUrl('RahulB'), is_primary: false, order: 1, verified: false, created_at: '2024-02-01' },
    ],
    basics: {
      user_id: '2',
      height_cm: 178,
      education: 'B.Tech, IIT Delhi',
      work_title: 'Senior Software Engineer',
      company: 'Microsoft',
      drinking: 'socially',
      smoking: 'never',
      wants_kids: 'want',
      settling_timeline: '1_2_years',
      exercise: 'daily',
    },
    sindhi: {
      user_id: '2',
      sindhi_fluency: 'conversational',
      religion: 'hindu',
      gotra: 'Amil',
      generation: 'sindhi_born',
      dietary: 'non_vegetarian',
      festivals: ['Chaliha Sahib', 'Diwali', 'Holi'],
      family_involvement: 'very_involved',
    },
    personality: {
      user_id: '2',
      prompts: [
        { prompt_id: '1', prompt_text: 'My simple pleasures', answer: 'Sunday morning papad with chai at Nani\'s house' },
        { prompt_id: '2', prompt_text: 'I geek out on', answer: 'Old Hindi songs, especially Sindhi folk remixes' },
      ],
      interests: ['Music', 'Cricket', 'Coding', 'Travel', 'Fitness'],
      bio: 'Software engineer by day, amateur musician by night.',
      languages: ['Sindhi', 'Hindi', 'English', 'Marathi'],
    },
    cultural_score: 88,
    cultural_badge: 'Excellent',
    cultural_breakdown: { fluency: 14, religion: 16, dietary: 12, festivals: 16, family_values: 16, generation: 14 },
    kundli_score: 24,
    kundli_tier: 'Good',
    kundli_breakdown: { varna: 1, vashya: 2, tara: 3, yoni: 3, graha_maitri: 5, gana: 4, bhakut: 3, nadi: 3 },
    common_interests: ['Travel', 'Music', 'Fitness'],
    distance_km: 12,
  },
  {
    user: {
      id: '3',
      phone: '+919876543212',
      first_name: 'Kavita',
      date_of_birth: '1997-11-03',
      age: 28,
      gender: 'woman',
      city: 'Ahmedabad',
      country: 'India',
      intent: 'open',
      show_me: 'men',
      bio: 'Doctor in training. Love exploring street food and hidden gems in every city. My Sindhi is rusty but my heart is 100% Sindhi.',
      verified: false,
      profile_completeness: 70,
      created_at: '2024-02-10',
      updated_at: '2024-03-05',
    },
    photos: [
      { id: 'p3', user_id: '3', url: avatarUrl('Kavita'), is_primary: true, order: 0, verified: false, created_at: '2024-02-10' },
      { id: 'p3b', user_id: '3', url: avatarUrl('KavitaB'), is_primary: false, order: 1, verified: false, created_at: '2024-02-10' },
      { id: 'p3c', user_id: '3', url: avatarUrl('KavitaC'), is_primary: false, order: 2, verified: false, created_at: '2024-02-10' },
      { id: 'p3d', user_id: '3', url: avatarUrl('KavitaD'), is_primary: false, order: 3, verified: false, created_at: '2024-02-10' },
    ],
    basics: {
      user_id: '3',
      height_cm: 160,
      education: 'MBBS, BJ Medical College',
      work_title: 'Resident Doctor',
      company: 'Civil Hospital',
      drinking: 'never',
      smoking: 'never',
      wants_kids: 'open',
      settling_timeline: '3_5_years',
      exercise: 'sometimes',
    },
    sindhi: {
      user_id: '3',
      sindhi_fluency: 'basic',
      religion: 'hindu',
      generation: '2nd_gen',
      dietary: 'vegetarian',
      festivals: ['Diwali', 'Navratri'],
      family_involvement: 'somewhat',
    },
    personality: {
      user_id: '3',
      prompts: [
        { prompt_id: '1', prompt_text: 'My most controversial opinion', answer: 'Dal pakwan is overrated. There, I said it.' },
        { prompt_id: '2', prompt_text: 'Together we could', answer: 'Start a food blog documenting every Sindhi restaurant in India' },
      ],
      interests: ['Medicine', 'Food', 'Travel', 'Netflix', 'Dancing'],
      bio: 'Doctor in training with wanderlust.',
      languages: ['Hindi', 'English', 'Gujarati'],
    },
    cultural_score: 65,
    cultural_badge: 'Good',
    cultural_breakdown: { fluency: 8, religion: 14, dietary: 12, festivals: 10, family_values: 12, generation: 9 },
    kundli_score: 18,
    kundli_tier: 'Fair',
    common_interests: ['Travel', 'Food'],
    distance_km: 320,
  },
  {
    user: {
      id: '4',
      phone: '+971501234567',
      first_name: 'Arjun',
      date_of_birth: '1995-05-18',
      age: 30,
      gender: 'man',
      city: 'Dubai',
      country: 'UAE',
      intent: 'marriage',
      show_me: 'women',
      bio: 'Finance guy in Dubai. Born and raised Sindhi. Looking for someone who values both tradition and ambition. Fluent in 4 languages including sarcasm.',
      verified: true,
      profile_completeness: 95,
      created_at: '2024-01-20',
      updated_at: '2024-03-12',
    },
    photos: [
      { id: 'p4', user_id: '4', url: avatarUrl('Arjun'), is_primary: true, order: 0, verified: true, created_at: '2024-01-20' },
      { id: 'p4b', user_id: '4', url: avatarUrl('ArjunB'), is_primary: false, order: 1, verified: false, created_at: '2024-01-20' },
    ],
    basics: {
      user_id: '4',
      height_cm: 182,
      education: 'CFA, London Business School',
      work_title: 'Investment Banker',
      company: 'Goldman Sachs',
      drinking: 'socially',
      smoking: 'never',
      wants_kids: 'want',
      settling_timeline: 'asap',
      exercise: 'daily',
    },
    sindhi: {
      user_id: '4',
      sindhi_fluency: 'fluent',
      religion: 'hindu',
      gotra: 'Bhatia',
      generation: 'sindhi_born',
      dietary: 'non_vegetarian',
      festivals: ['Chaliha Sahib', 'Diwali', 'Jhulelal Jayanti', 'Holi'],
      family_involvement: 'very_involved',
    },
    personality: {
      user_id: '4',
      prompts: [
        { prompt_id: '1', prompt_text: 'The key to my heart is', answer: 'Someone who can hold a conversation in Sindhi and also debate global markets' },
        { prompt_id: '2', prompt_text: 'My Sindhi superpower', answer: 'I know every Sindhi family in Dubai within 2 degrees of separation' },
      ],
      interests: ['Finance', 'Cricket', 'Cars', 'Fine Dining', 'Travel'],
      bio: 'Finance guy in Dubai with Sindhi roots.',
      languages: ['Sindhi', 'Hindi', 'English', 'Arabic'],
    },
    cultural_score: 95,
    cultural_badge: 'Excellent',
    cultural_breakdown: { fluency: 18, religion: 16, dietary: 14, festivals: 17, family_values: 16, generation: 14 },
    kundli_score: 30,
    kundli_tier: 'Ideal',
    kundli_breakdown: { varna: 1, vashya: 2, tara: 3, yoni: 4, graha_maitri: 5, gana: 6, bhakut: 5, nadi: 4 },
    common_interests: ['Finance', 'Cricket', 'Travel'],
    distance_km: 1800,
  },
  {
    user: {
      id: '5',
      phone: '+447911123456',
      first_name: 'Neha',
      date_of_birth: '1999-01-28',
      age: 27,
      gender: 'woman',
      city: 'London',
      country: 'UK',
      intent: 'open',
      show_me: 'men',
      bio: 'Third-gen Sindhi in London trying to learn the language one Bollywood song at a time. Artist and dreamer. Probably painting right now.',
      verified: false,
      profile_completeness: 60,
      created_at: '2024-02-20',
      updated_at: '2024-03-01',
    },
    photos: [
      { id: 'p5', user_id: '5', url: avatarUrl('Neha'), is_primary: true, order: 0, verified: false, created_at: '2024-02-20' },
    ],
    basics: {
      user_id: '5',
      height_cm: 163,
      education: 'BA Fine Arts, Goldsmiths',
      work_title: 'Graphic Designer',
      company: 'Freelance',
      drinking: 'socially',
      smoking: 'socially',
      wants_kids: 'open',
      exercise: 'sometimes',
    },
    sindhi: {
      user_id: '5',
      sindhi_fluency: 'learning',
      religion: 'spiritual',
      generation: '3rd_gen',
      dietary: 'non_vegetarian',
      festivals: ['Diwali'],
      family_involvement: 'minimal',
    },
    personality: {
      user_id: '5',
      prompts: [
        { prompt_id: '1', prompt_text: 'I want someone who', answer: 'Can teach me Sindhi patiently and laugh with me when I butcher the pronunciation' },
        { prompt_id: '2', prompt_text: 'My idea of a perfect day', answer: 'Gallery hopping, a nice curry, and a walk along the Thames' },
      ],
      interests: ['Art', 'Design', 'Museums', 'Coffee', 'Vintage Shopping'],
      bio: 'Artist and dreamer in London.',
      languages: ['English', 'Hindi'],
    },
    cultural_score: 45,
    cultural_badge: 'Fair',
    cultural_breakdown: { fluency: 4, religion: 8, dietary: 8, festivals: 6, family_values: 10, generation: 9 },
    common_interests: ['Art', 'Coffee'],
    distance_km: 7200,
  },
  {
    user: {
      id: '6',
      phone: '+919876543216',
      first_name: 'Vikram',
      date_of_birth: '1994-09-12',
      age: 31,
      gender: 'man',
      city: 'Mumbai',
      country: 'India',
      intent: 'marriage',
      show_me: 'women',
      bio: 'Family business + startup founder. My mom has been sending me rishtas since I turned 25, so I thought I would take matters into my own hands.',
      verified: true,
      profile_completeness: 80,
      created_at: '2024-01-05',
      updated_at: '2024-03-09',
    },
    photos: [
      { id: 'p6', user_id: '6', url: avatarUrl('Vikram'), is_primary: true, order: 0, verified: true, created_at: '2024-01-05' },
      { id: 'p6b', user_id: '6', url: avatarUrl('VikramB'), is_primary: false, order: 1, verified: false, created_at: '2024-01-05' },
      { id: 'p6c', user_id: '6', url: avatarUrl('VikramC'), is_primary: false, order: 2, verified: false, created_at: '2024-01-05' },
    ],
    basics: {
      user_id: '6',
      height_cm: 175,
      education: 'B.Com, Jai Hind College',
      work_title: 'Founder & CEO',
      company: 'TechSindh Solutions',
      drinking: 'never',
      smoking: 'never',
      wants_kids: 'want',
      settling_timeline: 'asap',
      exercise: 'often',
    },
    sindhi: {
      user_id: '6',
      sindhi_fluency: 'fluent',
      religion: 'hindu',
      gotra: 'Chhapru',
      generation: 'sindhi_born',
      dietary: 'vegetarian',
      festivals: ['Chaliha Sahib', 'Jhulelal Jayanti', 'Diwali', 'Thadri'],
      family_involvement: 'very_involved',
    },
    personality: {
      user_id: '6',
      prompts: [
        { prompt_id: '1', prompt_text: 'A life goal of mine', answer: 'To build something that makes my family proud and my community stronger' },
        { prompt_id: '2', prompt_text: 'My Sindhi superpower', answer: 'I can negotiate anything down by 30%. It is in the blood.' },
      ],
      interests: ['Entrepreneurship', 'Cricket', 'Gym', 'Movies', 'Community Service'],
      bio: 'Family business + startup founder.',
      languages: ['Sindhi', 'Hindi', 'English'],
    },
    cultural_score: 97,
    cultural_badge: 'Excellent',
    cultural_breakdown: { fluency: 18, religion: 16, dietary: 16, festivals: 17, family_values: 16, generation: 14 },
    kundli_score: 32,
    kundli_tier: 'Ideal',
    kundli_breakdown: { varna: 1, vashya: 2, tara: 3, yoni: 4, graha_maitri: 5, gana: 6, bhakut: 6, nadi: 5 },
    common_interests: ['Cricket', 'Gym', 'Movies'],
    distance_km: 3,
  },
  {
    user: {
      id: '7',
      phone: '+919876543217',
      first_name: 'Simran',
      date_of_birth: '1997-04-07',
      age: 28,
      gender: 'woman',
      city: 'Bangalore',
      country: 'India',
      intent: 'casual',
      show_me: 'men',
      bio: 'Data scientist who loves dancing and biryani. Not sure what I am looking for yet, but I will know when I find it.',
      verified: true,
      profile_completeness: 75,
      created_at: '2024-02-15',
      updated_at: '2024-03-11',
    },
    photos: [
      { id: 'p7', user_id: '7', url: avatarUrl('Simran'), is_primary: true, order: 0, verified: true, created_at: '2024-02-15' },
      { id: 'p7b', user_id: '7', url: avatarUrl('SimranB'), is_primary: false, order: 1, verified: false, created_at: '2024-02-15' },
    ],
    basics: {
      user_id: '7',
      height_cm: 158,
      education: 'M.S. Data Science, IIIT',
      work_title: 'Data Scientist',
      company: 'Flipkart',
      drinking: 'socially',
      smoking: 'never',
      wants_kids: 'open',
      settling_timeline: 'not_sure',
      exercise: 'sometimes',
    },
    sindhi: {
      user_id: '7',
      sindhi_fluency: 'conversational',
      religion: 'hindu',
      generation: 'sindhi_born',
      dietary: 'non_vegetarian',
      festivals: ['Diwali', 'Holi', 'Chaliha Sahib'],
      family_involvement: 'somewhat',
    },
    personality: {
      user_id: '7',
      prompts: [
        { prompt_id: '1', prompt_text: 'We will get along if', answer: 'You can handle my terrible Sindhi jokes and my amazing biryani' },
      ],
      interests: ['Data', 'Dancing', 'Cooking', 'Hiking', 'Podcasts'],
      bio: 'Data scientist who loves dancing.',
      languages: ['Sindhi', 'Hindi', 'English', 'Kannada'],
    },
    cultural_score: 78,
    cultural_badge: 'Good',
    cultural_breakdown: { fluency: 14, religion: 14, dietary: 10, festivals: 14, family_values: 14, generation: 12 },
    kundli_score: 22,
    kundli_tier: 'Good',
    common_interests: ['Cooking', 'Dancing', 'Hiking'],
    distance_km: 900,
  },
  {
    user: {
      id: '8',
      phone: '+919876543218',
      first_name: 'Rohan',
      date_of_birth: '1993-12-25',
      age: 32,
      gender: 'man',
      city: 'Mumbai',
      country: 'India',
      intent: 'marriage',
      show_me: 'women',
      bio: 'CA by profession, foodie by passion. Looking for my partner in crime who appreciates both a good balance sheet and a great meal.',
      verified: true,
      profile_completeness: 88,
      created_at: '2024-01-10',
      updated_at: '2024-03-06',
    },
    photos: [
      { id: 'p8', user_id: '8', url: avatarUrl('Rohan'), is_primary: true, order: 0, verified: true, created_at: '2024-01-10' },
      { id: 'p8b', user_id: '8', url: avatarUrl('RohanB'), is_primary: false, order: 1, verified: false, created_at: '2024-01-10' },
      { id: 'p8c', user_id: '8', url: avatarUrl('RohanC'), is_primary: false, order: 2, verified: false, created_at: '2024-01-10' },
    ],
    basics: {
      user_id: '8',
      height_cm: 176,
      education: 'CA, ICAI',
      work_title: 'Chartered Accountant',
      company: 'Deloitte',
      drinking: 'socially',
      smoking: 'never',
      wants_kids: 'want',
      settling_timeline: 'asap',
      exercise: 'often',
    },
    sindhi: {
      user_id: '8',
      sindhi_fluency: 'fluent',
      religion: 'hindu',
      gotra: 'Sahiti',
      generation: 'sindhi_born',
      dietary: 'eggetarian',
      festivals: ['Chaliha Sahib', 'Diwali', 'Jhulelal Jayanti'],
      family_involvement: 'very_involved',
    },
    personality: {
      user_id: '8',
      prompts: [
        { prompt_id: '1', prompt_text: 'The best way to ask me out', answer: 'Invite me to try a new restaurant. Extra points if it is Sindhi food.' },
        { prompt_id: '2', prompt_text: 'I am looking for', answer: 'Someone who makes ordinary moments feel extraordinary' },
      ],
      interests: ['Food', 'Finance', 'Gym', 'Movies', 'Board Games'],
      bio: 'CA by profession, foodie by passion.',
      languages: ['Sindhi', 'Hindi', 'English'],
    },
    cultural_score: 91,
    cultural_badge: 'Excellent',
    cultural_breakdown: { fluency: 18, religion: 16, dietary: 13, festivals: 16, family_values: 14, generation: 14 },
    kundli_score: 26,
    kundli_tier: 'Good',
    common_interests: ['Food', 'Movies', 'Gym'],
    distance_km: 8,
  },
  {
    user: {
      id: '9',
      phone: '+919876543219',
      first_name: 'Ananya',
      date_of_birth: '2000-08-14',
      age: 25,
      gender: 'woman',
      city: 'Delhi',
      country: 'India',
      intent: 'open',
      show_me: 'men',
      bio: 'Law student at NLU. My grandparents have the best love story and I want mine to be just as epic. Loves debating, reading, and biryani.',
      verified: false,
      profile_completeness: 65,
      created_at: '2024-03-01',
      updated_at: '2024-03-10',
    },
    photos: [
      { id: 'p9', user_id: '9', url: avatarUrl('Ananya'), is_primary: true, order: 0, verified: false, created_at: '2024-03-01' },
      { id: 'p9b', user_id: '9', url: avatarUrl('AnanyaB'), is_primary: false, order: 1, verified: false, created_at: '2024-03-01' },
    ],
    basics: {
      user_id: '9',
      height_cm: 162,
      education: 'B.A. LLB, NLU Delhi',
      work_title: 'Law Student',
      drinking: 'never',
      smoking: 'never',
      wants_kids: 'open',
      settling_timeline: '3_5_years',
      exercise: 'sometimes',
    },
    sindhi: {
      user_id: '9',
      sindhi_fluency: 'conversational',
      religion: 'hindu',
      generation: 'sindhi_born',
      dietary: 'vegetarian',
      festivals: ['Diwali', 'Chaliha Sahib'],
      family_involvement: 'somewhat',
    },
    personality: {
      user_id: '9',
      prompts: [
        { prompt_id: '1', prompt_text: 'I am convinced that', answer: 'Every Sindhi family has at least one secret recipe they guard with their lives' },
      ],
      interests: ['Law', 'Debate', 'Reading', 'Writing', 'Music'],
      bio: 'Law student with a love for stories.',
      languages: ['Sindhi', 'Hindi', 'English', 'Punjabi'],
    },
    cultural_score: 72,
    cultural_badge: 'Good',
    cultural_breakdown: { fluency: 14, religion: 14, dietary: 12, festivals: 12, family_values: 12, generation: 8 },
    kundli_score: 16,
    kundli_tier: 'Fair',
    common_interests: ['Reading', 'Music'],
    distance_km: 1400,
  },
  {
    user: {
      id: '10',
      phone: '+919876543220',
      first_name: 'Karan',
      date_of_birth: '1996-02-10',
      age: 30,
      gender: 'man',
      city: 'Ahmedabad',
      country: 'India',
      intent: 'marriage',
      show_me: 'women',
      bio: 'Doctor, vegetarian, and can recite the entire Chalisa from memory. Looking for someone who shares my values and can tolerate my bad PJs.',
      verified: true,
      profile_completeness: 82,
      created_at: '2024-01-25',
      updated_at: '2024-03-07',
    },
    photos: [
      { id: 'p10', user_id: '10', url: avatarUrl('Karan'), is_primary: true, order: 0, verified: true, created_at: '2024-01-25' },
      { id: 'p10b', user_id: '10', url: avatarUrl('KaranB'), is_primary: false, order: 1, verified: false, created_at: '2024-01-25' },
      { id: 'p10c', user_id: '10', url: avatarUrl('KaranC'), is_primary: false, order: 2, verified: false, created_at: '2024-01-25' },
      { id: 'p10d', user_id: '10', url: avatarUrl('KaranD'), is_primary: false, order: 3, verified: false, created_at: '2024-01-25' },
    ],
    basics: {
      user_id: '10',
      height_cm: 180,
      education: 'MBBS, MD Cardiology',
      work_title: 'Cardiologist',
      company: 'Apollo Hospitals',
      drinking: 'never',
      smoking: 'never',
      wants_kids: 'want',
      settling_timeline: 'asap',
      exercise: 'daily',
    },
    sindhi: {
      user_id: '10',
      sindhi_fluency: 'fluent',
      religion: 'hindu',
      gotra: 'Dadu',
      generation: 'sindhi_born',
      dietary: 'vegetarian',
      festivals: ['Chaliha Sahib', 'Jhulelal Jayanti', 'Diwali', 'Thadri', 'Navratri'],
      family_involvement: 'very_involved',
    },
    personality: {
      user_id: '10',
      prompts: [
        { prompt_id: '1', prompt_text: 'My non-negotiable', answer: 'Respect for elders and a genuine heart' },
        { prompt_id: '2', prompt_text: 'My typical Sunday', answer: 'Morning temple visit, gym, family lunch with sai bhaji, and evening walk' },
        { prompt_id: '3', prompt_text: 'My Sindhi superpower', answer: 'I can diagnose your health AND your kundli compatibility' },
      ],
      interests: ['Medicine', 'Spirituality', 'Gym', 'Cricket', 'Cooking'],
      bio: 'Doctor with traditional values and modern outlook.',
      languages: ['Sindhi', 'Hindi', 'English', 'Gujarati'],
    },
    cultural_score: 98,
    cultural_badge: 'Excellent',
    cultural_breakdown: { fluency: 18, religion: 16, dietary: 16, festivals: 18, family_values: 16, generation: 14 },
    kundli_score: 34,
    kundli_tier: 'Ideal',
    kundli_breakdown: { varna: 1, vashya: 2, tara: 3, yoni: 4, graha_maitri: 5, gana: 6, bhakut: 7, nadi: 6 },
    common_interests: ['Gym', 'Cricket', 'Cooking'],
    distance_km: 315,
  },
];

const futureDate = (hoursFromNow: number) => {
  const d = new Date();
  d.setHours(d.getHours() + hoursFromNow);
  return d.toISOString();
};

export const mockMatches: Match[] = [
  {
    id: 'm1',
    user: mockProfiles[0].user,
    photos: mockProfiles[0].photos,
    matched_at: '2024-03-10T14:30:00Z',
    last_message: {
      id: 'msg1',
      match_id: 'm1',
      sender_id: '1',
      content: 'Hey! I saw you love dal pakwan too. What is your favorite spot in Mumbai?',
      type: 'text',
      read: false,
      created_at: '2024-03-12T10:15:00Z',
    },
    unread_count: 2,
    is_online: true,
    first_msg_by: 'me',
    first_msg_locked: false,
    is_dissolved: false,
    extended_once: false,
    expires_at: futureDate(36),
  },
  {
    id: 'm2',
    user: mockProfiles[6].user,
    photos: mockProfiles[6].photos,
    matched_at: '2024-03-08T09:00:00Z',
    last_message: {
      id: 'msg2',
      match_id: 'm2',
      sender_id: 'me',
      content: 'That is amazing! I love Bangalore too. What area are you in?',
      type: 'text',
      read: true,
      created_at: '2024-03-11T16:20:00Z',
    },
    unread_count: 0,
    is_online: false,
    first_msg_by: 'me',
    first_msg_locked: true,
    is_dissolved: false,
    extended_once: false,
    expires_at: futureDate(3),
  },
  {
    id: 'm3',
    user: mockProfiles[2].user,
    photos: mockProfiles[2].photos,
    matched_at: new Date().toISOString(),
    unread_count: 0,
    is_online: true,
    first_msg_locked: false,
    is_dissolved: false,
    extended_once: false,
    expires_at: futureDate(48),
  },
];

export const mockLikes: Like[] = [
  {
    id: 'l1',
    from_user: mockProfiles[1].user,
    from_photos: mockProfiles[1].photos,
    type: 'like',
    created_at: '2024-03-12T08:00:00Z',
  },
  {
    id: 'l2',
    from_user: mockProfiles[3].user,
    from_photos: mockProfiles[3].photos,
    type: 'like',
    created_at: '2024-03-11T20:00:00Z',
  },
  {
    id: 'l3',
    from_user: mockProfiles[5].user,
    from_photos: mockProfiles[5].photos,
    type: 'like',
    created_at: '2024-03-10T15:00:00Z',
  },
];

export const mockMessages: Message[] = [
  {
    id: 'msg-1',
    match_id: 'm1',
    sender_id: 'me',
    content: 'Hi Priya! Love your profile. The sai bhaji comment got me.',
    type: 'text',
    read: true,
    created_at: '2024-03-10T15:00:00Z',
  },
  {
    id: 'msg-2',
    match_id: 'm1',
    sender_id: '1',
    content: 'Haha thank you! Are you a sai bhaji fan too?',
    type: 'text',
    read: true,
    created_at: '2024-03-10T15:05:00Z',
  },
  {
    id: 'msg-3',
    match_id: 'm1',
    sender_id: 'me',
    content: 'The biggest! My mom makes the best one. Though I am sure yours gives competition.',
    type: 'text',
    read: true,
    created_at: '2024-03-10T15:10:00Z',
  },
  {
    id: 'msg-4',
    match_id: 'm1',
    sender_id: '1',
    content: 'Oh you have no idea. Challenge accepted! We should do a cook-off sometime.',
    type: 'text',
    read: true,
    created_at: '2024-03-10T16:00:00Z',
  },
  {
    id: 'msg-5',
    match_id: 'm1',
    sender_id: 'me',
    content: 'Deal! But first, what is your go-to spot for Sindhi food in Mumbai?',
    type: 'text',
    read: true,
    created_at: '2024-03-11T09:00:00Z',
  },
  {
    id: 'msg-6',
    match_id: 'm1',
    sender_id: '1',
    content: 'Kailash Parbat, obviously! Their dal pakwan is unmatched.',
    type: 'text',
    read: true,
    created_at: '2024-03-11T09:30:00Z',
  },
  {
    id: 'msg-7',
    match_id: 'm1',
    sender_id: '1',
    content: 'Hey! I saw you love dal pakwan too. What is your favorite spot in Mumbai?',
    type: 'text',
    read: false,
    created_at: '2024-03-12T10:15:00Z',
  },
];

export const mockIcebreakers: Icebreaker[] = [
  { id: 'ice1', text: 'What Sindhi dish reminds you of home?', category: 'culture' },
  { id: 'ice2', text: 'What is your favorite festival memory?', category: 'culture' },
  { id: 'ice3', text: 'If you could live in any city, where would it be?', category: 'lifestyle' },
  { id: 'ice4', text: 'What is the most Sindhi thing about you?', category: 'fun' },
];

export const cities: City[] = [
  { name: 'Mumbai', country: 'India', display: 'Mumbai, India' },
  { name: 'Delhi', country: 'India', display: 'Delhi, India' },
  { name: 'Bangalore', country: 'India', display: 'Bangalore, India' },
  { name: 'Pune', country: 'India', display: 'Pune, India' },
  { name: 'Ahmedabad', country: 'India', display: 'Ahmedabad, India' },
  { name: 'Hyderabad', country: 'India', display: 'Hyderabad, India' },
  { name: 'Chennai', country: 'India', display: 'Chennai, India' },
  { name: 'Kolkata', country: 'India', display: 'Kolkata, India' },
  { name: 'Jaipur', country: 'India', display: 'Jaipur, India' },
  { name: 'Indore', country: 'India', display: 'Indore, India' },
  { name: 'Jodhpur', country: 'India', display: 'Jodhpur, India' },
  { name: 'Udaipur', country: 'India', display: 'Udaipur, India' },
  { name: 'Surat', country: 'India', display: 'Surat, India' },
  { name: 'Vadodara', country: 'India', display: 'Vadodara, India' },
  { name: 'Nagpur', country: 'India', display: 'Nagpur, India' },
  { name: 'Lucknow', country: 'India', display: 'Lucknow, India' },
  { name: 'Chandigarh', country: 'India', display: 'Chandigarh, India' },
  { name: 'Bhopal', country: 'India', display: 'Bhopal, India' },
  { name: 'Thane', country: 'India', display: 'Thane, India' },
  { name: 'Rajkot', country: 'India', display: 'Rajkot, India' },
  { name: 'Dubai', country: 'UAE', display: 'Dubai, UAE' },
  { name: 'Abu Dhabi', country: 'UAE', display: 'Abu Dhabi, UAE' },
  { name: 'London', country: 'UK', display: 'London, UK' },
  { name: 'New York', country: 'USA', display: 'New York, USA' },
  { name: 'Toronto', country: 'Canada', display: 'Toronto, Canada' },
  { name: 'Singapore', country: 'Singapore', display: 'Singapore' },
  { name: 'Hong Kong', country: 'China', display: 'Hong Kong' },
  { name: 'Sydney', country: 'Australia', display: 'Sydney, Australia' },
  { name: 'Nairobi', country: 'Kenya', display: 'Nairobi, Kenya' },
  { name: 'Lagos', country: 'Nigeria', display: 'Lagos, Nigeria' },
];

export const promptOptions = [
  'A life goal of mine',
  'The way to my heart is',
  'My Sindhi superpower',
  'My simple pleasures',
  'I geek out on',
  'My most controversial opinion',
  'Together we could',
  'I am convinced that',
  'My non-negotiable',
  'My typical Sunday',
  'The best way to ask me out',
  'I am looking for',
  'We will get along if',
  'I want someone who',
  'My idea of a perfect day',
];

export const interestOptions = [
  'Reading', 'Travel', 'Cooking', 'Yoga', 'Photography',
  'Music', 'Cricket', 'Coding', 'Fitness', 'Dancing',
  'Art', 'Design', 'Coffee', 'Food', 'Movies',
  'Hiking', 'Podcasts', 'Meditation', 'Gaming', 'Writing',
  'Fashion', 'Gardening', 'Running', 'Swimming', 'Tennis',
  'Volunteering', 'Entrepreneurship', 'Finance', 'Medicine', 'Law',
  'Spirituality', 'Board Games', 'Karaoke', 'Dogs', 'Cats',
];
