import Foundation
import SwiftUI

// MARK: - Language Enum

enum Language: String, CaseIterable, Identifiable {
    case en, hi, sd
    var id: String { rawValue }
    var displayName: String {
        switch self {
        case .en: return "English"
        case .hi: return "हिन्दी"
        case .sd: return "سنڌي"
        }
    }
}

// MARK: - LocalizationManager

class LocalizationManager: ObservableObject {
    static let shared = LocalizationManager()

    private let languageKey = "app_language"

    @Published var currentLanguage: Language {
        didSet {
            UserDefaults.standard.set(currentLanguage.rawValue, forKey: languageKey)
        }
    }

    init() {
        let saved = UserDefaults.standard.string(forKey: languageKey) ?? Language.en.rawValue
        self.currentLanguage = Language(rawValue: saved) ?? .en
    }

    func t(_ key: String) -> String {
        guard let langDict = translations[currentLanguage.rawValue],
              let value = langDict[key] else {
            // Fallback to English
            return translations["en"]?[key] ?? key
        }
        return value
    }

    // MARK: - Translations

    private let translations: [String: [String: String]] = [
        "en": [
            // Navigation
            "nav.discover": "Discover",
            "nav.likedYou": "Liked You",
            "nav.matches": "Matches",
            "nav.family": "Family",
            "nav.profile": "Profile",
            "nav.settings": "Settings",
            "nav.notifications": "Notifications",
            // Discover
            "discover.title": "Discover",
            "discover.filters": "Filters",
            "discover.noMoreProfiles": "No more profiles",
            "discover.noMoreProfilesMessage": "We've run out of profiles nearby. Try adjusting your filters or check back later!",
            "discover.like": "Like",
            "discover.pass": "Pass",
            "discover.likesUsedUp": "You have used all 50 likes for today. Come back tomorrow!",
            "discover.adjustFilters": "Adjust Filters",
            "discover.completeProfile": "Complete your profile",
            "discover.completeProfileHint": "Sindhi Identity & Chatti details get 3x more matches",
            "discover.inviteFriends": "Invite Sindhi Friends",
            "discover.itsAMatch": "It's a Match!",
            "discover.sendMessage": "Send Message",
            "discover.keepDiscovering": "Keep Discovering",
            "discover.seeBreakdown": "See breakdown",
            "discover.interests": "Interests",
            "discover.languages": "Languages",
            "discover.about": "About",
            "discover.compatibility": "Compatibility",
            "discover.culturalCompatibility": "Cultural Compatibility",
            "discover.kundliMatch": "Kundli Match",
            // Discover Filters
            "filter.title": "Filters",
            "filter.basic": "Basic",
            "filter.showMe": "Show Me",
            "filter.ageRange": "Age Range",
            "filter.heightRange": "Height Range",
            "filter.verifiedOnly": "Verified Profiles Only",
            "filter.intentAndInterests": "Intent & Interests",
            "filter.intent": "Intent",
            "filter.interests": "Interests",
            "filter.selected": "selected",
            "filter.communityAndCulture": "Community & Culture",
            "filter.religion": "Religion",
            "filter.sindhiFluency": "Sindhi Fluency",
            "filter.generation": "Generation",
            "filter.dietary": "Dietary",
            "filter.gotra": "Gotra",
            "filter.lifestyle": "Lifestyle",
            "filter.education": "Education",
            "filter.smoking": "Smoking",
            "filter.drinking": "Drinking",
            "filter.exercise": "Exercise",
            "filter.wantsKids": "Wants Kids",
            "filter.reset": "Reset",
            "filter.apply": "Apply Filters",
            // Matches
            "matches.title": "Matches",
            "matches.yourMatches": "Your Matches",
            "matches.chats": "Chats",
            "matches.noMatchesYet": "No matches yet",
            "matches.startLiking": "Start liking to find your match",
            "matches.sendFirstMessage": "Send the first message!",
            // Chat
            "chat.typeMessage": "Type a message...",
            "chat.send": "Send",
            "chat.waitingForReply": "Waiting for reply",
            "chat.icebreaker": "Start the conversation with an icebreaker",
            "chat.breakTheIce": "Break the ice",
            "chat.online": "Online",
            "chat.timerActive": "Timer active",
            "chat.chatUnlocked": "Chat unlocked! You can now message freely",
            "chat.matchedSendMessage": "You matched! Send a message to start the conversation.",
            "chat.waitingForReplyFrom": "Waiting for %@ to reply...",
            // Inbox
            "inbox.likedYou": "Liked You",
            "inbox.noLikesYet": "No likes yet",
            "inbox.noLikesMessage": "When someone likes your profile, they will appear here. Keep your profile fresh!",
            // Profile
            "profile.myProfile": "My Profile",
            "profile.editProfile": "Edit Profile",
            "profile.completion": "Profile completion",
            "profile.completeness": "Profile Completeness",
            "profile.completeForMatches": "Complete your profile to get more matches",
            "profile.complete": "Complete",
            "profile.bio": "Bio",
            "profile.aboutMe": "About Me",
            "profile.sindhiIdentity": "Sindhi Identity",
            "profile.interests": "Interests",
            "profile.height": "Height",
            "profile.education": "Education",
            "profile.occupation": "Occupation",
            "profile.company": "Company",
            "profile.religion": "Religion",
            "profile.smoking": "Smoking",
            "profile.drinking": "Drinking",
            "profile.exercise": "Exercise",
            "profile.wantKids": "Want Kids",
            "profile.sindhiFluency": "Sindhi Fluency",
            "profile.dialect": "Dialect",
            "profile.motherTongue": "Mother Tongue",
            "profile.gotra": "Gotra",
            "profile.generation": "Generation",
            "profile.familyValues": "Family Values",
            "profile.foodPreference": "Food Preference",
            // Family
            "family.familyMode": "Family Mode",
            "family.invite": "Invite",
            "family.members": "Members",
            "family.suggestions": "Suggestions",
            "family.description": "Involve trusted family members in your match journey. They can view profiles and suggest matches based on your preferences.",
            "family.noMembers": "No family members",
            "family.noMembersMessage": "Invite up to 3 family members to help with your matches",
            "family.sendInvite": "Send Invite",
            "family.inviteFamily": "Invite Family",
            "family.privacyNotice": "Family members cannot see your chats, matches, or swipe activity.",
            "family.familySuggestions": "Family Suggestions",
            "family.noSuggestionsYet": "No suggestions yet",
            "family.noSuggestionsMessage": "Family members with suggest permissions can recommend matches for you",
            "family.suggestedBy": "Suggested by",
            "family.inviteFamilyMember": "Invite Family Member",
            "family.inviteDescription": "Share this code with a family member to join your match circle.",
            "family.generateInviteCode": "Generate Invite Code",
            "family.copyCode": "Copy Code",
            "family.shareInvite": "Share Invite",
            "family.memberLimit": "Maximum 3 family members allowed per account.",
            "family.permissions": "permissions",
            "family.viewProfile": "View Profile",
            "family.viewPhotos": "View Photos",
            "family.viewBasics": "View Basics",
            "family.viewSindhiIdentity": "View Sindhi Identity",
            "family.viewMatches": "View Matches",
            "family.suggestProfiles": "Suggest Profiles",
            "family.culturalScore": "Cultural Score",
            "family.kundliScore": "Kundli Score",
            "family.removeMember": "Remove Member",
            // Settings
            "settings.title": "Settings",
            "settings.language": "Language",
            "settings.theme": "Theme",
            "settings.notifications": "Notifications",
            "settings.privacy": "Privacy",
            "settings.account": "Account",
            "settings.logOut": "Log Out",
            "settings.deleteAccount": "Delete Account",
            "settings.discovery": "Discovery",
            "settings.appearance": "Appearance",
            "settings.about": "About",
            "settings.showMe": "Show Me",
            "settings.ageRange": "Age Range",
            "settings.verifiedOnly": "Verified Only",
            "settings.matches": "Matches",
            "settings.messages": "Messages",
            "settings.likes": "Likes",
            "settings.familyUpdates": "Family Updates",
            "settings.expiry": "Match Expiry Reminders",
            "settings.dailyPrompt": "Daily Prompts",
            "settings.newFeatures": "New Features",
            "settings.showInDiscovery": "Show in Discovery",
            "settings.incognitoMode": "Incognito Mode",
            "settings.displayFullName": "Display Full Name",
            "settings.snoozeProfile": "Snooze Profile",
            "settings.editProfile": "Edit Profile",
            "settings.familyMode": "Family Mode",
            "settings.logOutConfirm": "Log Out?",
            "settings.logOutMessage": "You'll need to verify your phone number again to log back in.",
            "settings.deleteAccountConfirm": "Delete Account?",
            "settings.deleteAccountMessage": "Your account will be scheduled for deletion in 30 days. You can recover it by logging back in.",
            "settings.delete": "Delete",
            "settings.appVersion": "App Version",
            "settings.termsOfService": "Terms of Service",
            "settings.privacyPolicy": "Privacy Policy",
            "settings.communityGuidelines": "Community Guidelines",
            "settings.min": "Min",
            "settings.max": "Max",
            // Common
            "common.loading": "Loading",
            "common.error": "Error",
            "common.success": "Success",
            "common.cancel": "Cancel",
            "common.save": "Save",
            "common.done": "Done",
            "common.or": "or",
            "common.back": "Back",
            "common.next": "Next",
            "common.cultural": "Cultural",
            // Auth
            "auth.enterPhone": "Enter your phone number",
            "auth.sendVerification": "We'll send you a verification code",
            "auth.phoneNumber": "Phone number",
            "auth.continue": "Continue",
            "auth.securityNote": "Your number is encrypted and never shared",
            "auth.legalText": "By continuing, you agree to our Terms of Service and Privacy Policy",
            "auth.verifyNumber": "Verify your number",
            "auth.enterCode": "Enter the 6-digit code sent to",
            "auth.demoCode": "Demo code: 123456",
            "auth.verify": "Verify",
            "auth.resendCodeIn": "Resend code in",
            "auth.resendCode": "Resend Code",
            "auth.maxResend": "Maximum resend attempts reached",
            // Onboarding
            "onboarding.step": "Step",
            "onboarding.continue": "Continue",
            "onboarding.whatsYourName": "What's your name?",
            "onboarding.birthday": "When's your birthday?",
            "onboarding.gender": "What's your gender?",
            "onboarding.addPhotos": "Add your photos",
            "onboarding.lookingFor": "What are you looking for?",
            "onboarding.whoToSee": "Who do you want to see?",
            "onboarding.allSet": "You're all set!",
            "onboarding.back": "Back",
            "onboarding.next": "Next",
            "onboarding.of": "of",
            "onboarding.firstName": "First name",
            "onboarding.dateOfBirth": "Date of Birth",
            "onboarding.youreAge": "You're %@ years old",
            "onboarding.mustBe18": "Must be 18+",
            "onboarding.photos": "photos",
            "onboarding.minRequired": "Min 1 required",
            "onboarding.main": "Main",
            "onboarding.city": "City",
            "onboarding.stateProvince": "State / Province",
            "onboarding.country": "Country",
            "onboarding.welcomeToCommunity": "Welcome to the MitiMaiti community,",
            "onboarding.startDiscovering": "Start Discovering",
            // Welcome
            "welcome.title": "MitiMaiti",
            "welcome.subtitle": "Where Sindhi Hearts Meet",
            "welcome.getStarted": "Get Started",
            "welcome.haveAccount": "I have an account",
            "welcome.culturalMatch": "Cultural Match",
            "welcome.kundli": "Kundli",
            "welcome.familyMode": "Family Mode",
            "welcome.respectFirst": "Respect-First",
            "welcome.sindhiCommunity": "Sindhi Community",
            "welcome.realProfiles": "Real Profiles",
            "welcome.howItWorks": "How It Works",
            "welcome.culturalMatchSub": "Find your perfect cultural match",
            "welcome.kundliSub": "Astrological compatibility",
            "welcome.familyModeSub": "Involve your family",
            "welcome.respectFirstSub": "Safe & respectful",
            "welcome.sindhiCommunitySub": "Global Sindhi network",
            "welcome.realProfilesSub": "Verified members",
            "welcome.step1Title": "Create Your Profile",
            "welcome.step1Sub": "Share your story, photos & Sindhi identity",
            "welcome.step2Title": "Discover Matches",
            "welcome.step2Sub": "Culturally scored compatibility with Kundli insights",
            "welcome.step3Title": "Connect Respectfully",
            "welcome.step3Sub": "Meaningful conversations with 24h response windows",
        ],
        "hi": [
            // Navigation
            "nav.discover": "खोजें",
            "nav.likedYou": "आपको पसंद किया",
            "nav.matches": "मिलान",
            "nav.family": "परिवार",
            "nav.profile": "प्रोफ़ाइल",
            "nav.settings": "सेटिंग्स",
            "nav.notifications": "सूचनाएं",
            // Discover
            "discover.title": "खोजें",
            "discover.filters": "फ़िल्टर",
            "discover.noMoreProfiles": "कोई प्रोफ़ाइल नहीं",
            "discover.noMoreProfilesMessage": "आस-पास कोई प्रोफ़ाइल नहीं बची। फ़िल्टर बदलें या बाद में देखें!",
            "discover.like": "पसंद",
            "discover.pass": "पास",
            "discover.likesUsedUp": "आपने आज की सभी 50 लाइक इस्तेमाल कर ली हैं। कल वापस आएं!",
            "discover.adjustFilters": "फ़िल्टर बदलें",
            "discover.completeProfile": "अपनी प्रोफ़ाइल पूरी करें",
            "discover.completeProfileHint": "सिंधी पहचान और चट्टी विवरण से 3 गुना अधिक मिलान मिलते हैं",
            "discover.inviteFriends": "सिंधी दोस्तों को आमंत्रित करें",
            "discover.itsAMatch": "मैच हो गया!",
            "discover.sendMessage": "संदेश भेजें",
            "discover.keepDiscovering": "खोज जारी रखें",
            "discover.seeBreakdown": "विवरण देखें",
            "discover.interests": "रुचियाँ",
            "discover.languages": "भाषाएँ",
            "discover.about": "जानकारी",
            "discover.compatibility": "अनुकूलता",
            "discover.culturalCompatibility": "सांस्कृतिक अनुकूलता",
            "discover.kundliMatch": "कुंडली मिलान",
            // Discover Filters
            "filter.title": "फ़िल्टर",
            "filter.basic": "बुनियादी",
            "filter.showMe": "मुझे दिखाएं",
            "filter.ageRange": "उम्र सीमा",
            "filter.heightRange": "ऊँचाई सीमा",
            "filter.verifiedOnly": "केवल सत्यापित प्रोफ़ाइल",
            "filter.intentAndInterests": "इरादा और रुचियाँ",
            "filter.intent": "इरादा",
            "filter.interests": "रुचियाँ",
            "filter.selected": "चुने गए",
            "filter.communityAndCulture": "समुदाय और संस्कृति",
            "filter.religion": "धर्म",
            "filter.sindhiFluency": "सिंधी प्रवीणता",
            "filter.generation": "पीढ़ी",
            "filter.dietary": "आहार",
            "filter.gotra": "गोत्र",
            "filter.lifestyle": "जीवनशैली",
            "filter.education": "शिक्षा",
            "filter.smoking": "धूम्रपान",
            "filter.drinking": "शराब",
            "filter.exercise": "व्यायाम",
            "filter.wantsKids": "बच्चे चाहते हैं",
            "filter.reset": "रीसेट",
            "filter.apply": "फ़िल्टर लागू करें",
            // Matches
            "matches.title": "मिलान",
            "matches.yourMatches": "आपके मिलान",
            "matches.chats": "चैट्स",
            "matches.noMatchesYet": "अभी कोई मिलान नहीं",
            "matches.startLiking": "अपना मिलान खोजने के लिए लाइक करना शुरू करें",
            "matches.sendFirstMessage": "पहला संदेश भेजें!",
            // Chat
            "chat.typeMessage": "संदेश लिखें...",
            "chat.send": "भेजें",
            "chat.waitingForReply": "जवाब का इंतज़ार",
            "chat.icebreaker": "बातचीत शुरू करें",
            "chat.breakTheIce": "बर्फ तोड़ें",
            "chat.online": "ऑनलाइन",
            "chat.timerActive": "टाइमर चालू",
            "chat.chatUnlocked": "चैट अनलॉक! अब आप स्वतंत्र रूप से संदेश भेज सकते हैं",
            "chat.matchedSendMessage": "मैच हो गया! बातचीत शुरू करने के लिए संदेश भेजें।",
            "chat.waitingForReplyFrom": "%@ के जवाब का इंतज़ार...",
            // Inbox
            "inbox.likedYou": "आपको पसंद किया",
            "inbox.noLikesYet": "अभी कोई पसंद नहीं",
            "inbox.noLikesMessage": "जब कोई आपकी प्रोफ़ाइल पसंद करेगा, तो वे यहाँ दिखेंगे। अपनी प्रोफ़ाइल अपडेट रखें!",
            // Profile
            "profile.myProfile": "मेरी प्रोफ़ाइल",
            "profile.editProfile": "प्रोफ़ाइल संपादित करें",
            "profile.completion": "प्रोफ़ाइल पूर्णता",
            "profile.completeness": "प्रोफ़ाइल पूर्णता",
            "profile.completeForMatches": "अधिक मिलान पाने के लिए प्रोफ़ाइल पूरी करें",
            "profile.complete": "पूर्ण",
            "profile.bio": "परिचय",
            "profile.aboutMe": "मेरे बारे में",
            "profile.sindhiIdentity": "सिंधी पहचान",
            "profile.interests": "रुचियाँ",
            "profile.height": "ऊँचाई",
            "profile.education": "शिक्षा",
            "profile.occupation": "व्यवसाय",
            "profile.company": "कंपनी",
            "profile.religion": "धर्म",
            "profile.smoking": "धूम्रपान",
            "profile.drinking": "शराब",
            "profile.exercise": "व्यायाम",
            "profile.wantKids": "बच्चे चाहते हैं",
            "profile.sindhiFluency": "सिंधी प्रवीणता",
            "profile.dialect": "बोली",
            "profile.motherTongue": "मातृभाषा",
            "profile.gotra": "गोत्र",
            "profile.generation": "पीढ़ी",
            "profile.familyValues": "पारिवारिक मूल्य",
            "profile.foodPreference": "भोजन वरीयता",
            // Family
            "family.familyMode": "परिवार मोड",
            "family.invite": "आमंत्रित करें",
            "family.members": "सदस्य",
            "family.suggestions": "सुझाव",
            "family.description": "अपने मिलान की यात्रा में विश्वसनीय परिवार के सदस्यों को शामिल करें। वे प्रोफ़ाइल देख सकते हैं और आपकी प्राथमिकताओं के आधार पर मिलान सुझा सकते हैं।",
            "family.noMembers": "कोई परिवार सदस्य नहीं",
            "family.noMembersMessage": "अपने मिलान में मदद के लिए 3 परिवार सदस्यों को आमंत्रित करें",
            "family.sendInvite": "आमंत्रण भेजें",
            "family.inviteFamily": "परिवार को आमंत्रित करें",
            "family.privacyNotice": "परिवार के सदस्य आपकी चैट, मिलान या स्वाइप गतिविधि नहीं देख सकते।",
            "family.familySuggestions": "परिवार के सुझाव",
            "family.noSuggestionsYet": "अभी कोई सुझाव नहीं",
            "family.noSuggestionsMessage": "सुझाव अनुमति वाले परिवार सदस्य आपके लिए मिलान सुझा सकते हैं",
            "family.suggestedBy": "द्वारा सुझाया गया",
            "family.inviteFamilyMember": "परिवार सदस्य को आमंत्रित करें",
            "family.inviteDescription": "अपने मिलान सर्कल में शामिल होने के लिए इस कोड को परिवार के सदस्य के साथ साझा करें।",
            "family.generateInviteCode": "आमंत्रण कोड बनाएं",
            "family.copyCode": "कोड कॉपी करें",
            "family.shareInvite": "आमंत्रण साझा करें",
            "family.memberLimit": "प्रति खाता अधिकतम 3 परिवार सदस्य।",
            "family.permissions": "अनुमतियाँ",
            "family.viewProfile": "प्रोफ़ाइल देखें",
            "family.viewPhotos": "फ़ोटो देखें",
            "family.viewBasics": "बुनियादी जानकारी देखें",
            "family.viewSindhiIdentity": "सिंधी पहचान देखें",
            "family.viewMatches": "मिलान देखें",
            "family.suggestProfiles": "प्रोफ़ाइल सुझाएं",
            "family.culturalScore": "सांस्कृतिक स्कोर",
            "family.kundliScore": "कुंडली स्कोर",
            "family.removeMember": "सदस्य हटाएं",
            // Settings
            "settings.title": "सेटिंग्स",
            "settings.language": "भाषा",
            "settings.theme": "थीम",
            "settings.notifications": "सूचनाएं",
            "settings.privacy": "गोपनीयता",
            "settings.account": "खाता",
            "settings.logOut": "लॉग आउट",
            "settings.deleteAccount": "खाता हटाएं",
            "settings.discovery": "खोज",
            "settings.appearance": "दिखावट",
            "settings.about": "जानकारी",
            "settings.showMe": "मुझे दिखाएं",
            "settings.ageRange": "उम्र सीमा",
            "settings.verifiedOnly": "केवल सत्यापित",
            "settings.matches": "मिलान",
            "settings.messages": "संदेश",
            "settings.likes": "पसंद",
            "settings.familyUpdates": "परिवार अपडेट",
            "settings.expiry": "मिलान समाप्ति अनुस्मारक",
            "settings.dailyPrompt": "दैनिक सुझाव",
            "settings.newFeatures": "नई सुविधाएं",
            "settings.showInDiscovery": "खोज में दिखाएं",
            "settings.incognitoMode": "गुप्त मोड",
            "settings.displayFullName": "पूरा नाम दिखाएं",
            "settings.snoozeProfile": "प्रोफ़ाइल स्नूज़",
            "settings.editProfile": "प्रोफ़ाइल संपादित करें",
            "settings.familyMode": "परिवार मोड",
            "settings.logOutConfirm": "लॉग आउट करें?",
            "settings.logOutMessage": "वापस लॉग इन करने के लिए आपको अपना फ़ोन नंबर फिर से सत्यापित करना होगा।",
            "settings.deleteAccountConfirm": "खाता हटाएं?",
            "settings.deleteAccountMessage": "आपका खाता 30 दिनों में हटाने के लिए निर्धारित होगा। वापस लॉग इन करके आप इसे पुनर्प्राप्त कर सकते हैं।",
            "settings.delete": "हटाएं",
            "settings.appVersion": "ऐप संस्करण",
            "settings.termsOfService": "सेवा की शर्तें",
            "settings.privacyPolicy": "गोपनीयता नीति",
            "settings.communityGuidelines": "समुदाय दिशानिर्देश",
            "settings.min": "न्यूनतम",
            "settings.max": "अधिकतम",
            // Common
            "common.loading": "लोड हो रहा है",
            "common.error": "त्रुटि",
            "common.success": "सफल",
            "common.cancel": "रद्द करें",
            "common.save": "सहेजें",
            "common.done": "पूर्ण",
            "common.or": "या",
            "common.back": "वापस",
            "common.next": "अगला",
            "common.cultural": "सांस्कृतिक",
            // Auth
            "auth.enterPhone": "अपना फ़ोन नंबर दर्ज करें",
            "auth.sendVerification": "हम आपको एक सत्यापन कोड भेजेंगे",
            "auth.phoneNumber": "फ़ोन नंबर",
            "auth.continue": "जारी रखें",
            "auth.securityNote": "आपका नंबर एन्क्रिप्टेड है और कभी साझा नहीं किया जाता",
            "auth.legalText": "जारी रखकर, आप हमारी सेवा की शर्तों और गोपनीयता नीति से सहमत हैं",
            "auth.verifyNumber": "अपना नंबर सत्यापित करें",
            "auth.enterCode": "भेजे गए 6-अंकीय कोड दर्ज करें",
            "auth.demoCode": "डेमो कोड: 123456",
            "auth.verify": "सत्यापित करें",
            "auth.resendCodeIn": "कोड फिर भेजें",
            "auth.resendCode": "कोड फिर भेजें",
            "auth.maxResend": "अधिकतम पुनः भेजने के प्रयास पूरे हुए",
            // Onboarding
            "onboarding.step": "चरण",
            "onboarding.continue": "जारी रखें",
            "onboarding.whatsYourName": "आपका नाम क्या है?",
            "onboarding.birthday": "आपका जन्मदिन कब है?",
            "onboarding.gender": "आपका लिंग क्या है?",
            "onboarding.addPhotos": "अपनी फ़ोटो जोड़ें",
            "onboarding.lookingFor": "आप क्या ढूंढ रहे हैं?",
            "onboarding.whoToSee": "आप किसे देखना चाहते हैं?",
            "onboarding.allSet": "आप तैयार हैं!",
            "onboarding.back": "वापस",
            "onboarding.next": "अगला",
            "onboarding.of": "का",
            "onboarding.firstName": "पहला नाम",
            "onboarding.dateOfBirth": "जन्म तिथि",
            "onboarding.youreAge": "आपकी उम्र %@ साल है",
            "onboarding.mustBe18": "18+ होना आवश्यक",
            "onboarding.photos": "फ़ोटो",
            "onboarding.minRequired": "कम से कम 1 आवश्यक",
            "onboarding.main": "मुख्य",
            "onboarding.city": "शहर",
            "onboarding.stateProvince": "राज्य / प्रांत",
            "onboarding.country": "देश",
            "onboarding.welcomeToCommunity": "MitiMaiti समुदाय में आपका स्वागत है,",
            "onboarding.startDiscovering": "खोज शुरू करें",
            // Welcome
            "welcome.title": "मिटीमैटी",
            "welcome.subtitle": "जहाँ सिंधी दिल मिलते हैं",
            "welcome.getStarted": "शुरू करें",
            "welcome.haveAccount": "मेरा खाता है",
            "welcome.culturalMatch": "सांस्कृतिक मिलान",
            "welcome.kundli": "कुंडली",
            "welcome.familyMode": "परिवार मोड",
            "welcome.respectFirst": "सम्मान-पहले",
            "welcome.sindhiCommunity": "सिंधी समुदाय",
            "welcome.realProfiles": "असली प्रोफ़ाइल",
            "welcome.howItWorks": "यह कैसे काम करता है",
            "welcome.culturalMatchSub": "अपना सही सांस्कृतिक मिलान खोजें",
            "welcome.kundliSub": "ज्योतिषीय अनुकूलता",
            "welcome.familyModeSub": "अपने परिवार को शामिल करें",
            "welcome.respectFirstSub": "सुरक्षित और सम्मानजनक",
            "welcome.sindhiCommunitySub": "वैश्विक सिंधी नेटवर्क",
            "welcome.realProfilesSub": "सत्यापित सदस्य",
            "welcome.step1Title": "अपनी प्रोफ़ाइल बनाएं",
            "welcome.step1Sub": "अपनी कहानी, फ़ोटो और सिंधी पहचान साझा करें",
            "welcome.step2Title": "मिलान खोजें",
            "welcome.step2Sub": "कुंडली अंतर्दृष्टि के साथ सांस्कृतिक अनुकूलता स्कोर",
            "welcome.step3Title": "सम्मानपूर्वक जुड़ें",
            "welcome.step3Sub": "24 घंटे की प्रतिक्रिया विंडो के साथ सार्थक बातचीत",
        ],
        "sd": [
            // Navigation
            "nav.discover": "ڳوليو",
            "nav.likedYou": "توهان کي پسند ڪيو",
            "nav.matches": "ميلاپ",
            "nav.family": "خاندان",
            "nav.profile": "پروفائل",
            "nav.settings": "سيٽنگون",
            "nav.notifications": "اطلاعون",
            // Discover
            "discover.title": "ڳوليو",
            "discover.filters": "فلٽر",
            "discover.noMoreProfiles": "ڪو پروفائل ناهي",
            "discover.noMoreProfilesMessage": "ويجهو ڪو پروفائل نه مليو. فلٽر تبديل ڪريو يا بعد ۾ ڏسو!",
            "discover.like": "پسند",
            "discover.pass": "ڇڏيو",
            "discover.likesUsedUp": "اڄ جون سڀ 50 لائيڪ استعمال ٿي ويون. سڀاڻي واپس اچو!",
            "discover.adjustFilters": "فلٽر تبديل ڪريو",
            "discover.completeProfile": "پنهنجو پروفائل مڪمل ڪريو",
            "discover.completeProfileHint": "سنڌي سڃاڻپ ۽ چٽي تفصيلن سان 3 ڀيرا وڌيڪ ميلاپ ملندا",
            "discover.inviteFriends": "سنڌي دوستن کي دعوت ڏيو",
            "discover.itsAMatch": "ميلاپ ٿي ويو!",
            "discover.sendMessage": "پيغام موڪليو",
            "discover.keepDiscovering": "ڳولا جاري رکو",
            "discover.seeBreakdown": "تفصيل ڏسو",
            "discover.interests": "دلچسپيون",
            "discover.languages": "ٻوليون",
            "discover.about": "بابت",
            "discover.compatibility": "مطابقت",
            "discover.culturalCompatibility": "ثقافتي مطابقت",
            "discover.kundliMatch": "ڪنڊلي ميلاپ",
            // Discover Filters
            "filter.title": "فلٽر",
            "filter.basic": "بنيادي",
            "filter.showMe": "مون کي ڏيکاريو",
            "filter.ageRange": "عمر جي حد",
            "filter.heightRange": "قد جي حد",
            "filter.verifiedOnly": "صرف تصديق ٿيل پروفائل",
            "filter.intentAndInterests": "ارادو ۽ دلچسپيون",
            "filter.intent": "ارادو",
            "filter.interests": "دلچسپيون",
            "filter.selected": "چونڊيل",
            "filter.communityAndCulture": "برادري ۽ ثقافت",
            "filter.religion": "مذهب",
            "filter.sindhiFluency": "سنڌي ڳالهائڻ",
            "filter.generation": "نسل",
            "filter.dietary": "خوراڪ",
            "filter.gotra": "گوٽر",
            "filter.lifestyle": "طرز زندگي",
            "filter.education": "تعليم",
            "filter.smoking": "تماڪو",
            "filter.drinking": "شراب",
            "filter.exercise": "ورزش",
            "filter.wantsKids": "ٻار گهري ٿا",
            "filter.reset": "ري سيٽ",
            "filter.apply": "فلٽر لاڳو ڪريو",
            // Matches
            "matches.title": "ميلاپ",
            "matches.yourMatches": "توهان جا ميلاپ",
            "matches.chats": "چيٽس",
            "matches.noMatchesYet": "اڃا ڪو ميلاپ ناهي",
            "matches.startLiking": "پنهنجو ميلاپ ڳولڻ لاءِ لائيڪ ڪرڻ شروع ڪريو",
            "matches.sendFirstMessage": "پهريون پيغام موڪليو!",
            // Chat
            "chat.typeMessage": "پيغام لکو...",
            "chat.send": "موڪليو",
            "chat.waitingForReply": "جواب جو انتظار",
            "chat.icebreaker": "ڳالهه ٻولهه شروع ڪريو",
            "chat.breakTheIce": "برف ٽوڙيو",
            "chat.online": "آن لائن",
            "chat.timerActive": "ٽائمر فعال",
            "chat.chatUnlocked": "چيٽ کولي وئي! هاڻي توهان آزاديءَ سان پيغام موڪلي سگهو ٿا",
            "chat.matchedSendMessage": "ميلاپ ٿي ويو! ڳالهه ٻولهه شروع ڪرڻ لاءِ پيغام موڪليو.",
            "chat.waitingForReplyFrom": "%@ جي جواب جو انتظار...",
            // Inbox
            "inbox.likedYou": "توهان کي پسند ڪيو",
            "inbox.noLikesYet": "اڃا ڪا پسند ناهي",
            "inbox.noLikesMessage": "جڏهن ڪو توهان جي پروفائل پسند ڪندو، اهي هتي نظر ايندا. پنهنجي پروفائل تازي رکو!",
            // Profile
            "profile.myProfile": "منهنجو پروفائل",
            "profile.editProfile": "پروفائل ايڊٽ ڪريو",
            "profile.completion": "پروفائل مڪمل",
            "profile.completeness": "پروفائل مڪمليت",
            "profile.completeForMatches": "وڌيڪ ميلاپ حاصل ڪرڻ لاءِ پروفائل مڪمل ڪريو",
            "profile.complete": "مڪمل",
            "profile.bio": "تعارف",
            "profile.aboutMe": "منهنجي باري ۾",
            "profile.sindhiIdentity": "سنڌي سڃاڻپ",
            "profile.interests": "دلچسپيون",
            "profile.height": "قد",
            "profile.education": "تعليم",
            "profile.occupation": "پيشو",
            "profile.company": "ڪمپني",
            "profile.religion": "مذهب",
            "profile.smoking": "تماڪو",
            "profile.drinking": "شراب",
            "profile.exercise": "ورزش",
            "profile.wantKids": "ٻار گهري ٿا",
            "profile.sindhiFluency": "سنڌي ڳالهائڻ",
            "profile.dialect": "ٻولي",
            "profile.motherTongue": "مادري ٻولي",
            "profile.gotra": "گوٽر",
            "profile.generation": "نسل",
            "profile.familyValues": "خانداني قدر",
            "profile.foodPreference": "کاڌي پسند",
            // Family
            "family.familyMode": "خاندان موڊ",
            "family.invite": "دعوت ڏيو",
            "family.members": "ميمبر",
            "family.suggestions": "تجويزون",
            "family.description": "پنهنجي ميلاپ جي سفر ۾ ڀروسيمند خاندان جا ميمبر شامل ڪريو. اهي پروفائل ڏسي سگهن ٿا ۽ توهان جي پسند جي بنياد تي ميلاپ تجويز ڪري سگهن ٿا.",
            "family.noMembers": "ڪو خاندان جو ميمبر ناهي",
            "family.noMembersMessage": "پنهنجي ميلاپ ۾ مدد لاءِ 3 خاندان جا ميمبر دعوت ڏيو",
            "family.sendInvite": "دعوت موڪليو",
            "family.inviteFamily": "خاندان کي دعوت ڏيو",
            "family.privacyNotice": "خاندان جا ميمبر توهان جون چيٽون، ميلاپ يا سوائپ سرگرمي نٿا ڏسي سگهن.",
            "family.familySuggestions": "خاندان جون تجويزون",
            "family.noSuggestionsYet": "اڃا ڪا تجويز ناهي",
            "family.noSuggestionsMessage": "تجويز جي اجازت رکندڙ خاندان جا ميمبر توهان لاءِ ميلاپ تجويز ڪري سگهن ٿا",
            "family.suggestedBy": "تجويز ڪندڙ",
            "family.inviteFamilyMember": "خاندان جو ميمبر دعوت ڏيو",
            "family.inviteDescription": "پنهنجي ميلاپ دائري ۾ شامل ٿيڻ لاءِ هي ڪوڊ خاندان جي ميمبر سان شيئر ڪريو.",
            "family.generateInviteCode": "دعوت ڪوڊ ٺاهيو",
            "family.copyCode": "ڪوڊ نقل ڪريو",
            "family.shareInvite": "دعوت شيئر ڪريو",
            "family.memberLimit": "في اڪائونٽ وڌ ۾ وڌ 3 خاندان جا ميمبر.",
            "family.permissions": "اجازتون",
            "family.viewProfile": "پروفائل ڏسو",
            "family.viewPhotos": "تصويرون ڏسو",
            "family.viewBasics": "بنيادي ڄاڻ ڏسو",
            "family.viewSindhiIdentity": "سنڌي سڃاڻپ ڏسو",
            "family.viewMatches": "ميلاپ ڏسو",
            "family.suggestProfiles": "پروفائل تجويز ڪريو",
            "family.culturalScore": "ثقافتي سڪور",
            "family.kundliScore": "ڪنڊلي سڪور",
            "family.removeMember": "ميمبر هٽايو",
            // Settings
            "settings.title": "سيٽنگون",
            "settings.language": "ٻولي",
            "settings.theme": "ٿيم",
            "settings.notifications": "اطلاعون",
            "settings.privacy": "رازداري",
            "settings.account": "اڪائونٽ",
            "settings.logOut": "لاگ آئوٽ",
            "settings.deleteAccount": "اڪائونٽ ختم ڪريو",
            "settings.discovery": "ڳولا",
            "settings.appearance": "ظاهر",
            "settings.about": "بابت",
            "settings.showMe": "مون کي ڏيکاريو",
            "settings.ageRange": "عمر جي حد",
            "settings.verifiedOnly": "صرف تصديق ٿيل",
            "settings.matches": "ميلاپ",
            "settings.messages": "پيغام",
            "settings.likes": "پسند",
            "settings.familyUpdates": "خاندان جا اپڊيٽ",
            "settings.expiry": "ميلاپ ختم ٿيڻ جي ياددهاني",
            "settings.dailyPrompt": "روزانه تجويزون",
            "settings.newFeatures": "نئون خصوصيتون",
            "settings.showInDiscovery": "ڳولا ۾ ڏيکاريو",
            "settings.incognitoMode": "گمنام موڊ",
            "settings.displayFullName": "پورو نالو ڏيکاريو",
            "settings.snoozeProfile": "پروفائل اسنوز",
            "settings.editProfile": "پروفائل ايڊٽ ڪريو",
            "settings.familyMode": "خاندان موڊ",
            "settings.logOutConfirm": "لاگ آئوٽ ڪريو؟",
            "settings.logOutMessage": "واپس لاگ ان ڪرڻ لاءِ توهان کي پنهنجو فون نمبر ٻيهر تصديق ڪرڻو پوندو.",
            "settings.deleteAccountConfirm": "اڪائونٽ ختم ڪريو؟",
            "settings.deleteAccountMessage": "توهان جو اڪائونٽ 30 ڏينهن ۾ ختم ڪرڻ لاءِ مقرر ٿيندو. واپس لاگ ان ڪري توهان ان کي بحال ڪري سگهو ٿا.",
            "settings.delete": "ختم ڪريو",
            "settings.appVersion": "ايپ ورزن",
            "settings.termsOfService": "سروس جون شرطون",
            "settings.privacyPolicy": "رازداري پاليسي",
            "settings.communityGuidelines": "برادري جون هدايتون",
            "settings.min": "گهٽ ۾ گهٽ",
            "settings.max": "وڌ ۾ وڌ",
            // Common
            "common.loading": "لوڊ ٿي رهيو آهي",
            "common.error": "غلطي",
            "common.success": "ڪامياب",
            "common.cancel": "رد ڪريو",
            "common.save": "محفوظ ڪريو",
            "common.done": "ٿيو",
            "common.or": "يا",
            "common.back": "واپس",
            "common.next": "اڳيان",
            "common.cultural": "ثقافتي",
            // Auth
            "auth.enterPhone": "پنهنجو فون نمبر داخل ڪريو",
            "auth.sendVerification": "اسان توهان کي تصديق جو ڪوڊ موڪلينداسين",
            "auth.phoneNumber": "فون نمبر",
            "auth.continue": "جاري رکو",
            "auth.securityNote": "توهان جو نمبر انڪرپٽ آهي ۽ ڪڏهن به شيئر نٿو ڪبو",
            "auth.legalText": "جاري رکڻ سان، توهان اسان جي سروس جي شرطن ۽ رازداري پاليسي سان متفق آهيو",
            "auth.verifyNumber": "پنهنجو نمبر تصديق ڪريو",
            "auth.enterCode": "موڪليل 6-عددي ڪوڊ داخل ڪريو",
            "auth.demoCode": "ڊيمو ڪوڊ: 123456",
            "auth.verify": "تصديق ڪريو",
            "auth.resendCodeIn": "ڪوڊ ٻيهر موڪليو",
            "auth.resendCode": "ڪوڊ ٻيهر موڪليو",
            "auth.maxResend": "وڌ ۾ وڌ ٻيهر موڪلڻ جون ڪوششون پوريون ٿيون",
            // Onboarding
            "onboarding.step": "قدم",
            "onboarding.continue": "جاري رکو",
            "onboarding.whatsYourName": "توهان جو نالو ڇا آهي؟",
            "onboarding.birthday": "توهان جو ڄمڻ ڏينهن ڪڏهن آهي؟",
            "onboarding.gender": "توهان جو جنس ڇا آهي؟",
            "onboarding.addPhotos": "پنهنجيون تصويرون شامل ڪريو",
            "onboarding.lookingFor": "توهان ڇا ڳولي رهيا آهيو؟",
            "onboarding.whoToSee": "توهان ڪنهن کي ڏسڻ چاهيو ٿا؟",
            "onboarding.allSet": "توهان تيار آهيو!",
            "onboarding.back": "واپس",
            "onboarding.next": "اڳيان",
            "onboarding.of": "مان",
            "onboarding.firstName": "پهريون نالو",
            "onboarding.dateOfBirth": "ڄمڻ جي تاريخ",
            "onboarding.youreAge": "توهان جي عمر %@ سال آهي",
            "onboarding.mustBe18": "18+ هجڻ ضروري آهي",
            "onboarding.photos": "تصويرون",
            "onboarding.minRequired": "گهٽ ۾ گهٽ 1 ضروري",
            "onboarding.main": "مکيه",
            "onboarding.city": "شهر",
            "onboarding.stateProvince": "صوبو / رياست",
            "onboarding.country": "ملڪ",
            "onboarding.welcomeToCommunity": "MitiMaiti برادري ۾ ڀلي ڪري آيا،",
            "onboarding.startDiscovering": "ڳولا شروع ڪريو",
            // Welcome
            "welcome.title": "مِٽِي مَئِٽِي",
            "welcome.subtitle": "جتي سنڌي دل ملن ٿا",
            "welcome.getStarted": "شروع ڪريو",
            "welcome.haveAccount": "منهنجو اڪائونٽ آهي",
            "welcome.culturalMatch": "ثقافتي ميلاپ",
            "welcome.kundli": "ڪنڊلي",
            "welcome.familyMode": "خاندان موڊ",
            "welcome.respectFirst": "عزت-پهريان",
            "welcome.sindhiCommunity": "سنڌي برادري",
            "welcome.realProfiles": "اصلي پروفائل",
            "welcome.howItWorks": "هي ڪيئن ڪم ڪندو",
            "welcome.culturalMatchSub": "پنهنجو بهترين ثقافتي ميلاپ ڳوليو",
            "welcome.kundliSub": "نجومي مطابقت",
            "welcome.familyModeSub": "پنهنجي خاندان کي شامل ڪريو",
            "welcome.respectFirstSub": "محفوظ ۽ عزت وارو",
            "welcome.sindhiCommunitySub": "عالمي سنڌي نيٽ ورڪ",
            "welcome.realProfilesSub": "تصديق ٿيل ميمبر",
            "welcome.step1Title": "پنهنجو پروفائل ٺاهيو",
            "welcome.step1Sub": "پنهنجي ڪهاڻي، تصويرون ۽ سنڌي سڃاڻپ شيئر ڪريو",
            "welcome.step2Title": "ميلاپ ڳوليو",
            "welcome.step2Sub": "ڪنڊلي بصيرت سان ثقافتي مطابقت سڪور",
            "welcome.step3Title": "عزت سان ڳنڍجو",
            "welcome.step3Sub": "24 ڪلاڪ جي جواب ونڊو سان بامعني ڳالهه ٻولهه",
        ],
    ]
}
